#!/bin/bash

# To use, add 'alias ghd=". ghd"' to your ~/.bashrc, and put ghd in your PATH.
#
# Switches to the given github url/repo.
# Clones to GHD_LOCATION, or /tmp/ghd if not set.
# Clones via https by default (set GHD_USE_SSH=1 for ssh).

function _ghd_run() {
  function maybe_pull() { # location_root repo_url target branch
    local location_root="$1"
    local repo_url="$2"
    local target="$3"
    local branch="$4"
    local directory="$location_root/$target"
    local branch_param=""
    local new_branch_param=""

    if [[ $is_question -eq 1 ]]; then
      new_branch_param="-b"
    fi

    if [[ $is_pull_requested -eq 0 ]] && [[ -d "$directory" ]]; then
      if [[ -n "$branch" ]]; then
        git -C "$directory" checkout $new_branch_param "$branch"
        return $?
      fi
      return 0
    fi

    if [[ -z "$location_root" ]]; then
      return 1
    fi

    if [[ -z "$target" ]] || [[ "$target" == '/' ]]; then
      return 0
    fi

    if [[ ! -d "$directory" ]]; then
      if [[ -n "$branch" ]]; then
        branch_param="--branch \"$branch\""
      fi
      git clone $branch_param -- "$repo_url" "$directory"
      return $?
    fi

    if [[ -d "$directory/.git" ]]; then
      git -C "$directory" pull --all

      if [[ -n "$branch" ]]; then
        git -C "$directory" checkout $new_branch_param "$branch"
      fi
      return $?
    fi

    return 0
  }

  function maybe_pull_all() { # location_root repo_owner branch
    local location_root="$1"
    local repo_owner="$2"
    local branch="$3"
    local repo_single_names
    local branch_param=""
    local directory

    if ! gh auth status > /dev/null 2>&1; then
      return 1
    fi

    repo_single_names="$(gh repo list "$repo_owner" --limit 10000 \
      | cut -f1 | cut -d/ -f2)"

    if [[ -n "$branch" ]]; then
      branch_param="--branch \"$branch\""
    fi

    for repo_single_name in ${repo_single_names}; do
      directory="$location_root/$repo_owner/$repo_single_name"
      maybe_pull \
        "$location_root" \
        "$repo_url/$repo_single_name" \
        "$repo_owner/$repo_single_name" \
        "$branch"
    done

    return $result
  }

  function get_repo_name() { # repo_url_or_name
    local repo_url_or_name="$1"
    local name
    name="$(echo "$repo_url_or_name" | \
      sed "s/$GITHUB_HTTPS_PREFIX//g" | \
      sed "s/$GITHUB_GIT_PREFIX//g" | \
      sed "s/$GITHUB_SUFFIX//g")"
    echo "$name"
  }

  function get_repo_url() { # repo_url_or_name
    local repo_url_or_name="$1"
    if [[ $repo_url_or_name =~ ^$GITHUB_HTTPS_PREFIX ]] || \
        [[ $repo_url_or_name =~ ^$GITHUB_GIT_PREFIX ]]; then
      echo "$repo_url_or_name"
    elif [[ $use_ssh -eq 1 ]]; then
      echo "git@github.com:$repo_url_or_name"
    else
      echo "https://github.com/$repo_url_or_name"
    fi
  }

  function search_local() { # name
    local name="$1"

    find $GHD_LOCATION -maxdepth 2 -name "*$name*" \
      | cut -c$((${#GHD_LOCATION}+2))-
  }

  function search_gh() { # name
    local name="$1"
    local repos
    local name_param=""
    local grep_pipe=""
    if [[ $is_plus -eq 1 ]]; then
      name_param="$name"
    fi

    if ! command -v gh > /dev/null 2>&1; then
      return 1
    fi

    if ! gh auth status > /dev/null 2>&1; then
      return 2
    fi

    repos="$(gh repo list "$name_param" --limit 10000 | cut -f1)"

    if [[ $is_plus -eq 1 ]]; then
      echo "$repos"
      return 0
    fi

    echo "$repos" | grep "$name"
  }

  function get_repo_list() { # name
    local name="$1"
    {
      search_local "$name"
      search_gh "$name"
    } | \
      awk 'NF' | \
      sort -u
  }

  function fzf_ghd() { # query matches -> choice
    local query="$1"
    local matches="$2"
    local dest
    local fzf_status

    if [[ -z "$matches" ]]; then
      return 1
    fi

    if ! declare -F __fzfcmd >/dev/null; then
      return 2
    fi

    readme_glob='[Rr][Ee][Aa][Dd][Mm][Ee].*'
    dest="$(echo "$matches" | \
      $(__fzfcmd) --query="$query" --preview=" \
        printf 'https://www.github.com/{}\n\n' && \
        ( \
          ( \
            ls $location_root/{}/$readme_glob > /dev/null 2>&1 && \
            $pager <(cat $location_root/{}/$readme_glob) \
          ) || \
          $pager <(gh repo view {}) \
        )" \
    )"
    fzf_status="$?"
    if [[ "$fzf_status" -ne 0 ]]; then
      return "$fzf_status";
    fi
    echo "$dest"
    return 0
  }

  function handle_single_name() { # name
    local single_name="$1"
    local matches
    local num_matches
    matches="$(get_repo_list "$single_name")"
    if [[ -z $matches ]]; then
      if fzf_ghd "$single_name" "$matches"; then
        return 0
      fi
      echo "No cloned repository, user, or organization found for: $single_name" >&2
      return 1
    fi

    num_matches="$(echo "$matches" | wc -l)"
    if [ "$num_matches" -eq 1 ]; then
      echo "$matches"
      return 0
    fi

    if fzf_ghd "$single_name" "$matches"; then
      return 0
    fi

    echo "Found multiple matches for $single_name:" >&2
    echo "$matches" >&2
    return 1
  }

  function maybe_create_repo() { # location_root repo_name
    local location_root="$1"
    local repo_name="$2"
    local repo_url

    if [[ -z "$repo_name" ]]; then
      return 1
    fi

    if [[ "$repo_name" == "/" ]]; then
      return 1
    fi

    if [[ "$repo_name" != *"/"* ]]; then
      return 1
    fi

    # Assume repo_name is a user/org format
    repo_url="$(get_repo_url "$repo_name")"

    if git ls-remote "$repo_url" >/dev/null 2>&1; then
      echo "Cannot create repo - already exists on github: $repo_name"
      return 2
    fi

    git init "$location_root/$repo_name"
    cd "$location_root/$repo_name"

    if ! gh auth status > /dev/null 2>&1; then
      git remote add origin "$repo_url"
    else
      gh repo create "$repo_name" --private --source .
      result=$?
      if [[ $result -ne 0 ]]; then
        cd -
        rm -rf "$location_root/$repo_name"
        return 3
      fi
    fi

    return 0
  }

  function find_target() { # repo_name
    local repo_name="$1"

    if [[ -z "$repo_name" ]]; then
      fzf_ghd '' "$(get_repo_list)"
      return $?
    fi

    if [[ "$repo_name" == "/" ]]; then
      return 0
    fi

    if [[ "$repo_name" == *"/"* ]]; then
      echo "$repo_name"
      return 0
    fi

    handle_single_name $repo_name
    return $?
  }

  local location_root="${GHD_LOCATION:-/tmp/ghd}"
  local use_ssh="${GHD_USE_SSH:-0}"
  local pager="${PAGER:-cat}"
  local repo_url_or_name="$1"

  local is_apply_all=0
  local is_pull_requested=0
  local is_question=0
  local is_plus=0
  while [[ $repo_url_or_name == *'*' ]] || \
    [[ $repo_url_or_name == *'!' ]] || \
    [[ $repo_url_or_name == *'?' ]] || \
    [[ $repo_url_or_name == *'+' ]]
  do
    if [[ $repo_url_or_name == *'*' ]]; then
      repo_url_or_name="${repo_url_or_name%?}"
      is_apply_all=1
    fi

    if [[ $repo_url_or_name == *'!' ]]; then
      repo_url_or_name="${repo_url_or_name%?}"
      is_pull_requested=1
    fi

    if [[ $repo_url_or_name == *'?' ]]; then
      repo_url_or_name="${repo_url_or_name%?}"
      is_question=1
    fi

    if [[ $repo_url_or_name == *'+' ]]; then
      repo_url_or_name="${repo_url_or_name%?}"
      is_plus=1
    fi
  done

  local GITHUB_HTTPS_PREFIX='^https:\/\/github\.com[:/]'
  local GITHUB_GIT_PREFIX='^git@github\.com[:/]'
  local GITHUB_SUFFIX='\.git$'

  local repo_name
  local branch
  local target
  local result
  local repo_url
  local new_branch_param=""

  mkdir -p "$location_root"

  repo_name="$(get_repo_name "$repo_url_or_name")"
  branch=""
  if [[ "$repo_name" == *"@"* ]]; then
    branch=$(echo $repo_name | cut -f2 -d@)
    repo_name=$(echo $repo_name | cut -f1 -d@)
  fi

  if [[ $is_plus -eq 1 ]]; then
    maybe_create_repo "$location_root" "$repo_name"
    result=$?
    if [[ $result -eq 0 ]]; then
      # This was a create repo request, and we've handled it.
      return 0
    elif [[ $result -ne 1 ]]; then
      # Something really bad happened.
      return $result
    fi
  fi

  if [[ -n "$branch" ]] && [[ -z "$repo_name" ]]; then
    if [[ $is_question -eq 1 ]]; then
      new_branch_param="-b"
    fi

    git checkout $new_branch_param "$branch"

    if [[ $is_pull_requested -eq 1 ]]; then
      git pull
    fi

    return $?
  fi

  if [[ $is_apply_all -eq 0 ]]; then
    target="$(find_target "$repo_name")"
    result=$?
    if [[ $result -ne 0 ]]; then
      return $result
    fi
  else
    target="$repo_name"
  fi

  repo_url="$(get_repo_url "$target")"

  if [[ $is_apply_all -eq 0 ]]; then
    maybe_pull "$location_root" "$repo_url" "$target" "$branch"
  else
    maybe_pull_all "$location_root" "$target" "$branch"
  fi

  result=$?
  if [[ $result -ne 0 ]]; then
    return $result
  fi

  if [[ -z "$branch" ]] && [[ $is_question -eq 1 ]]; then
    echo "$location_root/$target"
    return 0
  fi

  cd "$location_root/$target"
  return 0
}

_ghd_run $@
